### ISSUE TITLE
Create ActiveUser endpoint

### ISSUE THREAD

**Issue by mangan360** [Furlough-Friends/rota-flex-101#35] opened 2020-04-09 13:34 UTC
As a manager, when any employee leaves the company I want to be able to remove that user from the list of active employees. 

Acceptance Criteria: 
- Given a user leaves the company, when the manager hits the ActiveUser endpoint through Postman with the user's ID  and a boolean value of false then the active flag should be set to false in the database. 
- Given a user hits the ActiveUser endpoint with any value, when they don't have admin access then they should be prompted with the message "You don't have permissions to set users to active"

**Comment by floyd924** [comment] 2020-04-10 08:27
If the Employee class does not already have an 'isActive' field this will need to be added

**Comment by emab** [comment] 2020-06-04 08:54
We were having some discussion on how we do this. Are we keeping the inactive flag?

When someone is removed, is all there personal data being set to `null` and their inactive flag set as true?

**Comment by tjanowsk** [comment] 2020-06-08 12:21
Possibly duplicate of #134

**Comment by emab** [comment] 2020-06-13 11:11
Yeah I think if someone is inactive, they will stay in the system but have no engagements. If someone leaves the company, they are deleted in the way described in #134. 

We could add an "away" flag for staff members in a future version.

**Closed by emab** 2020-06-13 11:11 UTC
Labels: back-end, duplicate
